config:
  vstacker:
    model: test/shaft_2.ply
    environ: test/env.ply
    layers: 3
    dmin: 100
    range_x: 50
    range_y: 930
    env_tr: [0,-30,-190, 0,0,.707,.707]
  vcam:
    trim_y: 300
    trim_x: 1000
    frame_id: camera
  vrobo:
    org: [0,0,500]
    step_y: 150
    step_z: 15

config_tf:
  user1:
    parent_frame_id: base
  user2:
    parent_frame_id: base
