config:
  vstacker:
    model: test/shaft_2.ply
#    environ: test/env.ply
#    env_tr: [0,0,-190, 0,0,0.707,0.707]        #Tr from bucket
    environ: test/test.ply
    env_tr: [300,50,1000,0.707,0.707,0.0,0.0]   #Tr from bucket
    layers: 3
    dmin: 100
    range_x: 50
    range_y: 930
    margin_y: 110
  vcam:
    trim_y: 1000
    trim_x: 300
    frame_id: camera
  vrobo:
    org: [0,0,500]
    step_y: 150
    step_z: 15

config_tf:
  bucket:
    parent_frame_id: world
    transform:
      rotation:
        w: 0
        x: 0
        y: 0
        z: 1
      translation:
        x: 500
        y: 0
        z: -500

  prepro:
    parent_frame_id: base
    transform:
      translation:
        x: 254
        y: 485
        z: 233
      rotation:
        x: 0
        y: 0
        z: -0.707
        w: 0.707

