config:
  vstacker:
    model: test/shaft_2.ply
    environ: test/env.ply
    layers: 3
    dmin: 100
    range_x: 50
    range_y: 930
    margin_y: 110
    env_tr: [0,0,-190, 0,0,.707,.707]
  vcam:
    trim_y: 300
    trim_x: 1000
    frame_id: camera
  vrobo:
    org: [0,0,500]
    step_y: 150
    step_z: 15

config_tf:
  bucket:
    parent_frame_id: world
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 0
        y: -25
        z: 0
