cropper:
  cropR: 300
  cropZ: -450
  cropZup: 0
  ladC: 0
  ladW: 0
  mesh: 0
  nfmin: 0
  nfrad: 0
picker:
  azimuth:
    max: 180
    min: 0
  fitness:
    max: 1
    min: 0.66
  rmse:
    max: 5
    min: 0
  rotation:
    max: 180
    min: -180
  transX:
    max: 3000
    min: -3000
  transY:
    max: 3000
    min: -3000
prepro:
  box0_crop: 0
  box0_depth: 5
  box0_low: 0
  box0_points: 800
  box0_width: 300
  bucket_height: 233
  bucket_width: 962
  bucket_yclip: 0
  enable: 2
  ss_dist: 0
  ss_ry: 0
revolver:
  deg: 0
  enable: 0
rovi:
  pshift_genpc:
    calc:
      bw_diff: 8
      darkness: 5
  ycam:
    ExposureTimeLevel: 5
    camera:
      Gain: 0
    hdr:
      enabled: false
      pcgen_publish: false
      projector:
        Intensity: 0.2
    projector:
      Intensity: 250
rsim:
  org_rx: 0
  org_ry: 180
  org_rz: 90
  org_x: 300
  org_y: 400
  org_z: 700
  wd: 0
searcher:
  cutter:
    align: y
    base: 0
    crop: 0
    distance: 0
    offset: 0
    width: 0
  distance_threshold: 18
  feature_mesh: 4
  feature_radius: 9
  icp_threshold: 3
  normal_min_nn: 5
  normal_radius: 9
  repeat: 1
  rotate: 0
