cropper:
  cropR: 0
  cropZ: -450
  cropZup: 280
  ladC: 0
  ladW: 0
  mesh: 2
  nfmin: 0
  nfrad: 0
picker:
  azimuth:
    max: 180
    min: 0
  fitness:
    max: 1
    min: 0.66
  rmse:
    max: 5
    min: 0
  rotation:
    max: 180
    min: -180
  transX:
    max: 3000
    min: -3000
  transY:
    max: 3000
    min: -3000
prepro:
  box0_crop: 150
  box0_depth: 20
  box0_low: 100
  box0_points: 700
  box0_width: 50
  bucket_height: 300
  bucket_width: 960
  bucket_yclip: 170
  enable: 1
  ss_dist: -330
  ss_ry: 15
revolver:
  deg: 0
  enable: 1
rovi:
  pshift_genpc:
    calc:
      bw_diff: 8
      darkness: 5
  ycam:
    ExposureTimeLevel: 5
    camera:
      Gain: 0
    hdr:
      enabled: false
      pcgen_publish: false
      projector:
        Intensity: 0.2
    projector:
      Intensity: 250
rsim:
  org_rx: 0
  org_ry: 180
  org_rz: 90
  org_x: 200
  org_y: 0
  org_z: 600
  wd: 0
searcher:
  cutter:
    align: y
    base: -80
    crop: -5
    distance: 500
    offset: 85
    width: 7
  distance_threshold: 18
  feature_mesh: 4
  feature_radius: 9
  icp_threshold: 3
  normal_min_nn: 5
  normal_radius: 9
  repeat: 1
  rotate: 0
